routes:
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account
  /authors/:
    template: page-authors
  /tags/:
    template: page-tags
  /newsletter/:
    template: page-newsletter

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
