version: '3'

services:
  ghost:
    image: ghost:3.7.0
    container_name: ghost
    volumes:
      - /data/liebling:/var/lib/ghost/content/themes/liebling:Z
      - /data/liebling/src/ghost.db:/var/lib/ghost/content/data/ghost.db:Z
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368
